### ISSUE TITLE
add reference in vim-lsp wiki

### ISSUE THREAD

**Issue by prabirshrestha** [pdavydov108/vim-lsp-cquery#1]
would be good if you could add the link to this project here so others can find this project easily. https://github.com/prabirshrestha/vim-lsp/wiki/Servers-cquery

**Comment by pdavydov108** [comment]
Thanks for suggesting! I was going to ask you if it's ok to add a link there. I'll send you PR asap.

**Comment by prabirshrestha** [comment]
Feel free to edit the wiki. No need PRs.

**Comment by pdavydov108** [comment]
I've added a link to this plugin to wiki, and some instructions how to setup cquery.
